// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeQualityReportGen
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CodeQualityReportGenString = "6fd5e41c-ba69-492b-a787-cfd4e02c4190";
        public static Guid CodeQualityReportGen = new Guid(CodeQualityReportGenString);

        public const string CodeQualityWindowString = "ce2a0f92-d094-48c5-be02-b8624558136a";
        public static Guid CodeQualityWindow = new Guid(CodeQualityWindowString);

        public const string QualityOverviewWindowString = "7bda49d1-3062-4c71-9de5-956e509ee0b9";
        public static Guid QualityOverviewWindow = new Guid(QualityOverviewWindowString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyCommand = 0x0100;
        public const int QualityOverviewCommand = 0x0101;
    }
}