// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TestPerformanceReportGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "TestPerformanceReportGenerator.8d73f547-31c3-41db-a78e-d0369731ea87";
        public const string Name = "TestPerformanceReportGenerator";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Simone Lin";
        public const string Tags = "";
    }
}
