// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TestPerformanceReportGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodeQualityReportGen.8FD76D89-72D5-402D-81DB-DC28EFD14918";
        public const string Name = "CodeQualityReportGen";
        public const string Description = @"This extension generates html reports which reports the code metrics, test outcomes and line coverage. It can also generate an ""overview"" report which includes all the code metrics and test outcomes from previous reports. ";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "UCL Blueprints";
        public const string Tags = "";
    }
}
