// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TestPerformanceReportGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodeQualityReportGen.8d73f547-31c3-41db-a78e-d0369731ea87";
        public const string Name = "CodeQualityReportGen";
        public const string Description = @"This extension generates html reports which reports the code metrics, test outcomes and line coverage. It can also generate an ""../overview"" report which includes all the code metrics and test outcomes from previous reports. 
The reports will be stored in a directory called ""../Reports"" which can be found in the directory where the solution file (.sln) is stored.
The overview report will be stored in a directory called ""../Overview_Report"" which can be found in the directory where the solution file (.sln) is stored.Visual Studio Extension that";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "UCLBlueprints";
        public const string Tags = "";
    }
}
