// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DesignPatternDetection
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string DesignPatternDetectionString = "e1bd1dba-5143-40a4-ad26-62a390908d1e";
        public static Guid DesignPatternDetection = new Guid(DesignPatternDetectionString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyToolWindowCommand = 0x0100;
    }
}